# Generated by Django 2.2.6 on 2019-11-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoSucursal', models.IntegerField(default=0)),
                ('nombreSucursal', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(default=0)),
                ('fechaNacimiento', models.DateTimeField(verbose_name='Fecha de Nacimiento')),
                ('fechaVisita', models.DateTimeField(verbose_name='Fecha de visita')),
                ('HoraVisita', models.DateTimeField(verbose_name='Hora de visita')),
                ('codigoSucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservadehoras.Sucursal')),
            ],
        ),
    ]
